la_ticketing_info:
    path:     /info
    defaults: { _controller: LATicketingBundle:Ticketing:info }

la_ticketing_order:
    path:     /order/create
    defaults: { _controller: LATicketingBundle:Ticketing:orderCreate }

la_ticketing_buy:
    path:     /order/{id}/buy
    defaults: { _controller: LATicketingBundle:Ticketing:orderBuy }

la_ticketing_confirm:
    path:     /order/{id}/confirm
    defaults: { _controller: LATicketingBundle:Ticketing:orderConfirm }

la_ticketing_ticket_pdf:
    path:     /ticket/{id}
    defaults: { _controller: LATicketingBundle:Ticketing:generatePdf }
    
