services:
    la_ticketing.mailer:
        class: LA\TicketingBundle\Services\Mailer
        arguments:
            - "@mailer"
            - "@templating"
    la_ticketing.validator.ordercheck:                           
        class: LA\TicketingBundle\Validator\Constraints\OrderCheckValidator  
        arguments:
            - "@doctrine.orm.entity_manager"                                     
        tags:
            - { name: validator.constraint_validator, alias: la.order_check }
    la_ticketing.stripe_payment:
        class: LA\TicketingBundle\Services\StripePayment
        arguments:
            - "%stripe_key%"
            - "@doctrine.orm.entity_manager"

  